I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 41, in script
    Rplay sound "audio/buzz.wav"
Exception: Sayer 'Rplay' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 41, in script
    Rplay sound "audio/buzz.wav"
  File "/Applications/renpy-8.3.4-sdk/renpy/ast.py", line 2579, in execute
    Say.execute(self)
  File "/Applications/renpy-8.3.4-sdk/renpy/ast.py", line 581, in execute
    who = eval_who(self.who, self.who_fast)
  File "/Applications/renpy-8.3.4-sdk/renpy/ast.py", line 470, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'Rplay' is not defined.

macOS-14.6.1-arm64-arm-64bit arm64
Ren'Py 8.3.4.24120703
frostbound 1.0
Sun Dec 29 20:23:35 2024
